### PR TITLE
Fixing typescript definitions, closing #57

### PR DESCRIPTION
**Pull request by mikeesouth**
Fixing #57

### CODE REVIEW

**Comment by Vaccano** [comment]
Please merge this in!

Typescript is broken without it... :(

**Comment by mikeesouth** [comment]
ping @Vheissu

**Comment by mattbrooks2010** [comment]
This change alone may just result in a runtime error because the [amd module](https://github.com/Vheissu/Aurelia-Configuration/blob/master/dist/amd/aurelia-configuration.js#L10) is defined as `configure`.

**Comment by mikeesouth** [comment]
@mattbrooks2010 ok, how do we fix that? In my setup the above fix works perfectly but I understand that there are other setups and use cases. Can you help out to submit a better PR so that @Vheissu can merge it?

**Comment by mattbrooks2010** [comment]
@mikeesouth that's interesting. It's possible I was being misled by an issue or misunderstanding with the interplay between the TypeScript tooling in my IDE, `tsconfig.json` and `au build`.

I'd like to understand what's going on so will take another look this week weekend. 

I've reverted to `environment.ts` now, which won't work for me in all scenarios.

**Comment by mattbrooks2010** [comment]
@mikeesouth what version of the Aurelia CLI are you using?

    $ au -v
    $ 0.19.0

**Comment by mikeesouth** [comment]
@mattbrooks2010 I'm not using CLI. I'm using webpack and typescript. More or less based from this skeleton: https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-typescript-webpack

**Comment by mattbrooks2010** [comment]
OK, so I think we're seeing different problems then and I don't think mine are necessarily related to this PR. 

With `webpack` you're probably using `commonjs` modules, i.e. in the `./dist/commonjs` folder, correct?

The `./dist/amd` build appears to have some issues, if you compare it to the other module formats in the `dist` folder. I was able to get comparable output to the other module formats by removing [this line](https://github.com/Vheissu/Aurelia-Configuration/blob/master/tsconfig.amd.json#L6) and running `tsc -p tsconfig.amd.json`.

Even after doing this, and updating `aurelia.json` (CLI specific?) accordingly, I then ran into an issue where the plugin appeared to be looking in the bundled output for the config file - something I was trying to avoid as I need this file unbundled.

I probably wont pursue my issue further here, as the open issues aren't getting much attention.

Good luck with your PR!

**Comment by mikeesouth** [comment]
I'm using `es2015` modules.
Anyways, this fix may be too narrow (maybe only targeting `es2015` modules?) but I need this fix (or some more generic fix) in order to keep using this lib.
It seems like @Vheissu has alot on his plate so I think I'll look into alternative libs.

**Comment by fracz** [comment]
Can you release `1.0.9` with this fix, please?

**Pull request merged**
