### PR TITLE
Add support for arbitrary deep keys

### LINKED ISSUE #23: get() returns the parent object instead of a primitive value
### description

when retrieving config values via the `get()` function, the returned value is the object wrapping the value, and not the value itself.
### steps to reproduce
1. create a config file with the default configuration (don't change the file path or name), with a nested object, e.g.:
   
   ```
   {
       "exit": {
           "timeout": {
               "duration": 2000
           }
       }
   }
   ```
2. inject the config service into a view
3. after the app bootstrap, and the view is attached, attempt to retrieve a nested value, e.g.:
   
   ```
   let duration = this.config.get('exit.timeout.duration');
   ```
### expected result

the retrieved value reference (`duration`) should have the config primitive value, e.g. `2000`.
### actual result

the retrieved value reference holds the wrapping object instead, e.g. `{ "duration": 2000 }`.
### environment details
- **jspm version:** 1.0.4
- **OS:** linux ubuntu 15.10 64-bit
- **browser:** chromium 48.0.2564.116

### PR DESCRIPTION
**Pull request by nalch**
Fixes #23

### CODE REVIEW

**Comment by diegohb** [comment]
would love to see this make it in..

**Comment by maroy1986** [comment]
Is there a plan to merge/release this? I'm up to a point in a project where I would need this.
Thanks for your time!

**Comment by Vheissu** [comment]
Thanks for the PR. I'll get this released ASAP! Sorry for the delay.

**Comment by diegohb** [comment]
And I got impatient with pre-release bug I was trying to solve in my app and did the merge in a fork.. I’ve never done that before but feel free to pull it in .. I merged this plus the unit test bug fix and updated Audelia dependencies...

**Comment by diegohb** [comment]
It did solve my bug and work as expected though.. 👍😁

**Comment by maroy1986** [comment]
Did you plan on updating the package on NPM? Think you forgot to :)

**Pull request merged**
