### PR TITLE
Environment checking using strict checking

### PR DESCRIPTION
**Pull request by Scrunshes**
Pull request referring to issue #87.

### CODE REVIEW

**Comment by bas080** [comment]
@Scrunshes, I know it's annoying but you should use the same linebreaks as @Vheissu does. :worried:

**Comment by Scrunshes** [comment]
@bas080 what do you mean ?

**Comment by bas080** [comment]
@Scrunshes, noticed that the diff contains all the lines.

**Comment by Scrunshes** [comment]
That's because I wanted to clarify the method, I don't really see where the problem is...

**Comment by Vheissu** [comment]
I'm cool with the linebreaks in this, cheers for the PR. I'll merge and release this today.

**Pull request merged**
