### PR TITLE
added support for port number in host names

### PR DESCRIPTION
**Pull request by omniscient**
to fix https://github.com/Vheissu/aurelia-configuration/issues/90 which is a blocker for us.

### CODE REVIEW

**Comment by omniscient** [comment]
Dwayne, can you please review the PR?

**Comment by TomFoyster** [comment]
Any movement on this?

**Comment by Vheissu** [comment]
Sorry about this, I wasn't notified there was a PR for this repo. I'll release it today.

**Comment by maroy1986** [comment]
Excellent! Thanks!

**Pull request merged**
