### PR TITLE
fix(jspm): fix build output

### PR DESCRIPTION
**Pull request by JeroenVinke**
fixes https://github.com/Vheissu/Aurelia-Configuration/issues/43

Turns out the build task creates its own index.js file that points to a file with the same name as the package name. As aurelia-configration already had an index.js file, it got overwritten. 

Also, this also fixes the issue where you'd get a 404 for `aurelia-configuration@1.0.9.js` because there now is a file name "aurelia-configuration" (and this is the [main](https://github.com/Vheissu/Aurelia-Configuration/blob/master/package.json#L27)). Now JSPM can find the main file and creates the `aurelia-configuration@1.0.9.js` file correctly again.

a built version of this change can be installed via `jspm install aurelia-configuration=github:JeroenVinke/aurelia-configuration@built`

### CODE REVIEW

**Comment by bdatta1981** [comment]
@JeroenVinke Thanks for change. However, there is one more issue in the latest version. The typings file aurelia-configuration.d.ts is also not installed by JSPM install. Will you be able to fix it?

**Comment by JeroenVinke** [comment]
I believe you need to fetch the typescript definitions via the typings tool now: http://blog.durandal.io/2016/06/10/where-did-my-typescript-go/

Although, [this](https://github.com/Vheissu/Aurelia-Configuration/blob/master/dist/aurelia-configuration.d.ts#L211-L213) gave me an error

**Comment by bdatta1981** [comment]
Right. Even I got the same error. The d.ts does not have any module export. I think @Vheissu needs to update this too.

**Comment by mdenny-visaglobal** [comment]
Yep that's sorted it for me thanks heaps 👍

**Comment by Vheissu** [comment]
Thank you for this fix. I am in the process of switching over my plugin skeletons to address issues like this.  This plugin and my other plugins will also be written in TypeScript, so issues like this shouldn't occur once I've refactored this and the others.

**Pull request merged**
