### PR TITLE
Config file optional.

### PR DESCRIPTION
**Pull request by JoshMcCullough**
Merge other PRs first, if you intend to. This builds upon them, sort of. 

In general, I don't think the config file should be required, particularly when you're loading multiple, some of which may be optional. So I don't think it should throw an error if the file doesn't exist.

### CODE REVIEW

**Comment by Vheissu** [comment]
@JoshMcCullough Love your work buddy, thank you for submitting this PR.

**Comment by Vheissu** [comment]
@JoshMcCullough I think merging the other PR's has resulted in a merge conflict, would you mind sorting that out please mate and then I can merge this one in as well.

**Comment by JoshMcCullough** [comment]
Here, this should work better. Thanks!!

**Comment by JoshMcCullough** [comment]
Thanks for the quick work! When do you expect these PRs to make it into a release?

**Pull request merged**
